sudo: required
services: 
  - docker

before_install:
  - docker build -t robggarcia84/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true robggarcia84/react-test npm test

after_success:
  - docker build -t robggarcia84/multi-client-rob ./client
  - docker build -t robggarcia84/multi-nginx-rob ./nginx
  - docker build -t robggarcia84/multi-server-rob ./server 
  - docker build -t robggarcia84/multi-worker-rob ./worker
  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to DockerHub
  - docker push robggarcia84/multi-client-rob
  - docker push robggarcia84/multi-nginx-rob
  - docker push robggarcia84/multi-server-rob
  - docker push robggarcia84/multi-worker-rob